"use client";
import { useEffect,useState } from "react";
import { CheckCircle2,Loader2,Save,TriangleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

type Option={code:string;name:string};type Payload={worker:{name:string;workerRegister:string;origin:string;age:string;status:string;categoryMappingRequired:boolean;legacyCategoryCode:string|null};master:{categories:Option[];skills:Option[];experiences:Option[];placements:Option[]};form:{category:string;experience:string;skills:string[];placement:string;publicationConsent:boolean};salaryDisplay:string;contentStatus:string;readiness:{status:string;score:number;missing:string[];checks:Record<string,boolean>}};
export function WorkerEnrichmentFlow({workerRegister,enabled,editable}:{workerRegister:string;enabled:boolean;editable:boolean}){const[data,setData]=useState<Payload|null>(null);const[form,setForm]=useState<Payload["form"]>({category:"",experience:"",skills:[],placement:"",publicationConsent:false});const[loading,setLoading]=useState(enabled);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);
useEffect(()=>{if(!enabled)return;const controller=new AbortController();(async()=>{try{const response=await fetch(`/api/workers/${encodeURIComponent(workerRegister)}/enrichment`,{cache:"no-store",signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body.error??"LOAD_FAILED");setData(body);setForm(body.form);}catch(cause){if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:"LOAD_FAILED");}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[workerRegister,enabled]);
function toggleSkill(code:string){setForm((current)=>({...current,skills:current.skills.includes(code)?current.skills.filter((item)=>item!==code):[...current.skills,code]}));}
async function save(){setSaving(true);setError(null);try{const response=await fetch(`/api/workers/${encodeURIComponent(workerRegister)}/enrichment`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json();if(!response.ok)throw new Error(body.error??"SAVE_FAILED");setData((current)=>current?{...current,...body,form:body.form}:current);}catch(cause){setError(cause instanceof Error?cause.message:"SAVE_FAILED");}finally{setSaving(false);}}
if(!enabled)return <p className="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">Enrichment aktif setelah Neon, Google OAuth, Content Bridge, dan token encryption siap.</p>;if(loading)return <div className="flex min-h-40 items-center justify-center"><Loader2 className="animate-spin text-slate-400"/></div>;if(error&&!data)return <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">Gagal memuat enrichment: {error}</div>;if(!data)return null;
return <div className="space-y-5"><div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-[#0B1F3A]">{data.worker.name}</p><p className="text-xs text-slate-500">{data.worker.origin}{data.worker.age?` • ${data.worker.age} tahun`:""}{data.worker.status?` • ${data.worker.status}`:""}</p></div><Badge>{data.contentStatus}</Badge></div>{data.worker.categoryMappingRequired&&<p className="mt-3 flex gap-2 rounded-xl bg-amber-50 p-2 text-xs font-semibold text-amber-800"><TriangleAlert size={15}/>Legacy code {data.worker.legacyCategoryCode} perlu Mapping Register.</p>}</div>
<label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">Kategori</span><select disabled={!editable} value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})} className="min-h-12 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih kategori</option>{data.master.categories.map((o)=><option key={o.code} value={o.code}>{o.name}</option>)}</select></label>
<label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">Pengalaman</span><select disabled={!editable} value={form.experience} onChange={(e)=>setForm({...form,experience:e.target.value})} className="min-h-12 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih pengalaman</option>{data.master.experiences.map((o)=><option key={o.code} value={o.code}>{o.name}</option>)}</select></label>
<div><span className="mb-2 block text-xs font-bold text-slate-600">Keahlian</span><div className="flex flex-wrap gap-2">{data.master.skills.map((o)=>{const active=form.skills.includes(o.code);return <button type="button" disabled={!editable} key={o.code} onClick={()=>toggleSkill(o.code)} className={`min-h-10 rounded-full border px-3 text-xs font-semibold ${active?"border-[#0B1F3A] bg-[#0B1F3A] text-white":"border-slate-200 bg-white text-slate-600"}`}>{active&&<CheckCircle2 className="mr-1 inline" size={13}/>} {o.name}</button>;})}</div></div>
<label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">Penempatan utama untuk rate</span><select disabled={!editable} value={form.placement} onChange={(e)=>setForm({...form,placement:e.target.value})} className="min-h-12 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Pilih penempatan</option>{data.master.placements.map((o)=><option key={o.code} value={o.code}>{o.name}</option>)}</select></label>
<label className="flex min-h-12 items-center gap-3 rounded-xl border border-slate-200 bg-white px-3 text-sm"><input type="checkbox" disabled={!editable} checked={form.publicationConsent} onChange={(e)=>setForm({...form,publicationConsent:e.target.checked})}/><span>Izin publikasi telah dikonfirmasi</span></label>
<div className="rounded-xl border border-slate-200 p-3"><div className="flex items-center justify-between"><span className="text-sm font-semibold">Kesiapan konten</span><Badge>{data.readiness.score}% • {data.readiness.status}</Badge></div><p className="mt-1 text-xs text-slate-500">Rate: {data.salaryDisplay||"dihitung saat disimpan"} • Kurang: {data.readiness.missing.length?data.readiness.missing.join(", "):"tidak ada"}</p></div>
{error&&<p className="text-sm font-semibold text-red-600">{error}</p>}{editable&&<Button onClick={save} disabled={saving||!form.category||!form.experience||!form.skills.length||!form.placement} className="w-full gap-2"><Save size={17}/>{saving?"Menyimpan…":"Simpan & Hitung Rate"}</Button>}</div>;
}
