"use client";
import { useEffect, useMemo, useState } from "react";
import { Camera, RotateCw, ImageUp, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { prepareImage } from "@/modules/photo/client-image";
import { buildPhotoFilename, validatePhotoInput, type PhotoType } from "@/modules/photo/validation";
export function WorkerPhotoPrep({ workerRegister, workerName="PEKERJA", driveEnabled=false }: { workerRegister:string; workerName?:string; driveEnabled?:boolean }) {
  const [file,setFile]=useState<File|null>(null); const [rotation,setRotation]=useState(0); const [prepared,setPrepared]=useState<{blob:Blob;width:number;height:number}|null>(null); const [error,setError]=useState<string|null>(null); const [photoType,setPhotoType]=useState<PhotoType>("PROFILE");
  const previewUrl=useMemo(()=>file?URL.createObjectURL(file):null,[file]); useEffect(()=>()=>{ if(previewUrl) URL.revokeObjectURL(previewUrl); },[previewUrl]);
  async function onPrepare(){ if(!file)return; setError(null); try{ setPrepared(await prepareImage(file,{rotation})); }catch(cause){ setError(cause instanceof Error?cause.message:"Gagal menyiapkan foto"); } }
  return <div className="space-y-4"><div className="flex gap-2 overflow-x-auto pb-1">{(["PROFILE","FULLBODY","TRAINING","OTHER"] as PhotoType[]).map((type)=><button key={type} onClick={()=>setPhotoType(type)} className={`min-h-11 shrink-0 rounded-xl border px-3 text-xs font-bold ${photoType===type?"border-[#0B1F3A] bg-[#0B1F3A] text-white":"border-slate-200 bg-white text-slate-600"}`}>{type}</button>)}</div>
  <label className="flex min-h-28 cursor-pointer flex-col items-center justify-center gap-2 rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-4 text-center text-sm font-semibold text-slate-600"><ImageUp size={22}/><span>Ambil dari kamera atau galeri</span><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" capture={photoType==="PROFILE"?"user":"environment"} onChange={(event)=>{ const selected=event.target.files?.[0]??null; setPrepared(null);setRotation(0);setError(null); if(!selected){setFile(null);return;} const validation=validatePhotoInput({size:selected.size,mimeType:selected.type}); if(!validation.valid){setFile(null);setError(validation.message);return;} setFile(selected); }}/></label>
  {previewUrl&&<div className="relative mx-auto aspect-[4/5] w-full max-w-xs overflow-hidden rounded-2xl bg-slate-100"><img src={previewUrl} alt="Preview pekerja" className="h-full w-full object-cover transition" style={{transform:`rotate(${rotation}deg) scale(${rotation%180===0?1:1.2})`}}/><div className="pointer-events-none absolute inset-[8%] rounded-[40%] border border-dashed border-white/80"/></div>}
  {file&&<div className="flex gap-2"><Button variant="secondary" className="flex-1 gap-2" onClick={()=>{setRotation((value)=>(value+90)%360);setPrepared(null);}}><RotateCw size={17}/>Putar</Button><Button className="flex-1 gap-2" onClick={onPrepare}><Camera size={17}/>Siapkan</Button></div>}
  {prepared&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800"><div className="flex items-center gap-2 font-bold"><CheckCircle2 size={17}/>Foto siap upload</div><div className="mt-1 text-xs">{prepared.width}×{prepared.height}px • {Math.max(1,Math.round(prepared.blob.size/1024))} KB</div><div className="mt-1 break-all text-xs">{buildPhotoFilename({workerRegister,workerName,type:photoType,mimeType:"image/jpeg"})}</div></div>}
  {error&&<p className="text-sm font-semibold text-red-600">{error}</p>}{!driveEnabled&&<p className="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">Foto dapat dipreview, diputar, dan dikompres sekarang. Upload ke Google Drive tetap dikunci sampai Google OAuth dinyatakan sehat.</p>}</div>;
}
